In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame, Series
import seaborn as sns
from sklearn import datasets

In [28]:
r=pd.read_excel(("EDA_Shark_Tank_India.xlsx"))
r

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
0,1,1,BluePine Industries,Frozen Momos,1,50.0,5.0,1000.00,75.0,16.00,...,1,0,1,0,1,0,0,3,25.0,5.333333
1,1,2,Booz scooters,Renting e-bike for mobility in private spaces,1,40.0,15.0,266.67,40.0,50.00,...,1,0,0,0,1,0,0,2,20.0,25.000000
2,1,3,Heart up my Sleeves,Detachable Sleeves,1,25.0,10.0,250.00,25.0,30.00,...,0,1,0,0,1,0,0,2,12.5,15.000000
3,2,4,Tagz Foods,Healthy Potato Chips,1,70.0,1.0,7000.00,70.0,2.75,...,1,0,0,0,0,0,0,1,70.0,2.750000
4,2,5,Head and Heart,Brain Development Course,0,50.0,5.0,1000.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,34,113,Green Protein,Plant-Based Protein,0,60.0,2.0,3000.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
113,34,114,On2Cook,Fastest Cooking Device,0,100.0,1.0,10000.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
114,35,115,Jain Shikanji,Lemonade,1,40.0,8.0,500.00,40.0,30.00,...,1,1,1,0,1,0,0,4,10.0,7.500000
115,35,116,Woloo,Washroom Finder,0,50.0,4.0,1250.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
116,35,117,Elcare India,Carenting for Elders,0,100.0,2.5,4000.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000

In [3]:
r.columns

Index(['episode_number', 'pitch_number', 'brand_name', 'idea', 'deal',
       'pitcher_ask_amount', 'ask_equity', 'ask_valuation', 'deal_amount',
       'deal_equity', 'deal_valuation', 'ashneer_present', 'anupam_present',
       'aman_present', 'namita_present', 'vineeta_present', 'peyush_present',
       'ghazal_present', 'ashneer_deal', 'anupam_deal', 'aman_deal',
       'namita_deal', 'vineeta_deal', 'peyush_deal', 'ghazal_deal',
       'total_sharks_invested', 'amount_per_shark', 'equity_per_shark'],
      dtype='object')

In [4]:
e = r["episode_number"].unique()
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35], dtype=int64)

In [5]:
print(r['pitcher_ask_amount'].mean(), r['pitcher_ask_amount'].max(),r['pitcher_ask_amount'].min())

319.8547094871795 30000.0 0.00101

In [6]:
print(r['ask_equity'].mean(),r["ask_equity"].max(),r["ask_equity"].min())

5.188034188034188 25.0 0.25

In [7]:
print(r["ask_valuation"].mean(),r["ask_valuation"].max(),r["ask_valuation"].min())

3852.4624786324785 120000.0 0.01

In [8]:
df = r.groupby('episode_number')

In [9]:
df.first()

,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,deal_valuation,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
episode_number,,,,,,,,,,,,,,,,,,,,,
1,1,BluePine Industries,Frozen Momos,1,50.0,5.00,1000.00,75.0,16.00,468.75,...,1,0,1,0,1,0,0,3,25.000000,5.333333
2,4,Tagz Foods,Healthy Potato Chips,1,70.0,1.00,7000.00,70.0,2.75,2545.45,...,1,0,0,0,0,0,0,1,70.000000,2.750000
3,7,Qzense Labs,Food Freshness Detector,0,100.0,0.25,40000.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
4,10,Cosiq,Intelligent Skincare,1,50.0,7.50,666.67,50.0,25.00,200.00,...,0,1,0,0,1,0,0,2,25.000000,12.500000
5,13,Revamp Moto,E-Bike,1,100.0,1.00,10000.00,100.0,1.50,6666.67,...,0,1,1,0,0,0,0,2,50.000000,0.750000
6,16,Skippi Pops,Ice-Pops,1,45.0,5.00,900.00,100.0,15.00,666.67,...,1,1,1,1,1,0,0,5,20.000000,3.000000
7,19,Raising Superstars,Child Development App,0,100.0,2.00,5000.00,100.0,4.00,2500.00,...,1,0,1,0,0,0,0,2,50.000000,2.000000
8,22,Beyond Snack,Kerala Banana Chips,1,50.0,2.50,2000.00,50.0,2.50,2000.00,...,1,0,1,0,0,0,0,2,25.000000,1.250000
9,25,Altor,Smart Helmets,1,50.0,5.00,1000.00,50.0,7.00,714.29,...,0,0,1,1,0,0,0,2,25.000000,3.500000
10,28,Nuutjob,Male Intimate Hygiene,1,25.0,5.00,500.00,25.0,20.00,125.00,...,0,0,1,1,0,1,0,3,8.333333,6.666667
11,31,Gopal's 56,Fiber Ice Cream,0,30000.0,25.00,120000.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
12,34,Auli Lifestyle,Ayurvedic Products,1,75.0,4.00,1875.00,75.0,15.00,500.00,...,0,0,0,1,0,0,0,1,75.000000,15.000000
13,37,Annie,Braille Literary Device,1,30.0,5.00,600.00,105.0,3.00,3500.00,...,0,1,0,1,0,1,0,3,35.000000,1.000000
14,40,The Renal Project,Home Dialysis Treatment,1,100.0,3.00,3333.33,100.0,6.00,1666.67,...,0,0,1,1,0,0,0,2,50.000000,3.000000
15,43,Hammer Lifestyle,Smart Audio Products,1,30.0,3.00,1000.00,100.0,40.00,250.00,...,0,0,1,0,0,0,0,1,100.000000,40.000000
16,46,Bamboo India,Bamboo Products,1,80.0,4.00,2000.00,50.0,3.50,1428.57,...,1,1,0,0,0,0,0,2,25.000000,1.750000
17,50,Find Your Kicks India,Sneaker Resale,1,50.0,10.00,500.00,50.0,25.00,200.00,...,1,1,1,1,0,1,0,5,10.000000,5.000000
18,54,Mommy's Kitchen,Thin Crust Pizza,0,90.0,3.00,3000.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
19,58,Ethik,Leather-free Shoes,0,15.0,5.00,300.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
20,62,The State Plate,Delicacies,1,65.0,2.00,3250.00,40.0,3.00,1333.33,...,0,0,0,0,0,1,0,1,40.000000,3.000000
21,65,Get a Whey,Sugar-Free Icecream,1,100.0,8.00,1250.00,100.0,15.00,666.67,...,1,0,1,0,1,0,0,3,33.333333,5.000000
22,68,Hair Originals,Natural Hair Extensions,1,60.0,2.00,3000.00,60.0,4.00,1500.00,...,1,1,0,0,0,1,0,3,20.000000,1.333333
23,72,Namhya Foods,Ayurvedic Enriched Food,1,100.0,5.00,2000.00,50.0,10.00,500.00,...,0,0,1,0,0,0,0,1,50.000000,10.000000
24,76,The Sass Bar,Gifts,1,40.0,8.00,500.00,50.0,35.00,142.86,...,0,1,0,0,0,0,1,2,25.000000,17.500000
25,79,PawsIndia,Dog Products,1,50.0,4.00,1250.00,50.0,15.00,333.33,...,0,1,0,0,0,0,0,1,50.000000,15.000000
26,82,Isak Fragrances,Perfumes,1,50.0,8.00,625.00,50.0,50.00,100.00,...,0,0,0,0,0,1,0,1,50.000000,50.000000
27,85,Theka Coffee,Coffee Products,0,50.0,10.00,500.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
28,89,Humpy A2,Organic Milk Products,1,75.0,4.00,1875.00,100.0,15.00,666.67,...,0,0,0,0,1,1,1,3,33.333333,5.000000
29,92,Wakao Foods,Jackfruit Products,1,75.0,5.00,1500.00,75.0,21.00,357.14,...,0,0,0,1,1,0,1,3,25.000000,7.000000
30,95,Sippline Drinking Shields,Portable Glass Attachment,0,75.0,15.00,500.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
31,99,Scrapshala,Handmade Reusable Scrap Materials,0,50.0,10.00,500.00,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
32,103,Thea and Sid,Proposal Solutions,0,80.0,7.00,1142.86,0.0,0.00,0.00,...,0,0,0,0,0,0,0,0,0.000000,0.000000
33,107,Colour Me Mad,Insoles,1,40.0,10.00,400.00,40.0,25.00,160.00,...,0,0,0,1,0,0,0,1,40.000000,25.000000
34,111,Nomad Food Project,Bacon Jams,1,40.0,10.00,400.00,40.0,20.00,200.00,...,1,0,0,1,1,0,1,4,10.000000,5.000000
35,115,Jain Shikanji,Lemonade,1,40.0,8.00,500.00,40.0,30.00,133.33,...,1,1,1,0,1,0,0,4,10.000000,7.500000

In [10]:
t=[df.ask_valuation.min(),df.ask_valuation.max(),df.ask_equity.min(),df.ask_equity.max(),df.pitcher_ask_amount.min(),df.pitcher_ask_amount.max()]
pd.DataFrame(t)

episode_number,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
ask_valuation,250.0,1000.0,1875.00,500.0,50.0,500.0,666.67,746.67,1000.0,500.0,...,500.0,0.01000,1000.0,1500.00,500.0,500.0,583.33,400.0,400.0,500.0
ask_valuation,1000.0,7000.0,40000.00,1875.0,10000.0,10000.0,7500.00,2000.00,2000.0,1500.0,...,6500.0,10000.00000,1875.0,2857.14,30000.0,3750.0,5000.00,3500.0,10000.0,4000.0
ask_equity,5.0,1.0,0.25,4.0,1.0,1.0,1.00,2.50,2.5,2.0,...,1.0,1.00000,4.0,3.00,1.0,2.0,1.00,1.0,1.0,2.5
ask_equity,15.0,5.0,4.00,10.0,20.0,10.0,7.50,7.50,5.0,5.0,...,10.0,10.00000,5.0,5.00,15.0,10.0,7.00,10.0,10.0,8.0
pitcher_ask_amount,25.0,50.0,50.00,50.0,10.0,45.0,50.00,30.00,50.0,25.0,...,50.0,0.00101,50.0,75.00,50.0,50.0,35.00,35.0,30.0,40.0
pitcher_ask_amount,50.0,70.0,100.00,75.0,100.0,100.0,100.00,56.00,100.0,30.0,...,65.0,100.00000,90.0,100.00,300.0,75.0,200.00,40.0,100.0,100.0

In [11]:
k=(r[(r['total_sharks_invested']>1)])
k

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
0,1,1,BluePine Industries,Frozen Momos,1,50.00000,5.0,1000.00,75.00000,16.0,...,1,0,1,0,1,0,0,3,25.000000,5.333333
1,1,2,Booz scooters,Renting e-bike for mobility in private spaces,1,40.00000,15.0,266.67,40.00000,50.0,...,1,0,0,0,1,0,0,2,20.000000,25.000000
2,1,3,Heart up my Sleeves,Detachable Sleeves,1,25.00000,10.0,250.00,25.00000,30.0,...,0,1,0,0,1,0,0,2,12.500000,15.000000
9,4,10,Cosiq,Intelligent Skincare,1,50.00000,7.5,666.67,50.00000,25.0,...,0,1,0,0,1,0,0,2,25.000000,12.500000
11,4,12,Bummer,Underwear,1,75.00000,4.0,1875.00,75.00000,7.5,...,0,0,1,1,0,0,0,2,37.500000,3.750000
12,5,13,Revamp Moto,E-Bike,1,100.00000,1.0,10000.00,100.00000,1.5,...,0,1,1,0,0,0,0,2,50.000000,0.750000
15,6,16,Skippi Pops,Ice-Pops,1,45.00000,5.0,900.00,100.00000,15.0,...,1,1,1,1,1,0,0,5,20.000000,3.000000
18,7,19,Raising Superstars,Child Development App,0,100.00000,2.0,5000.00,100.00000,4.0,...,1,0,1,0,0,0,0,2,50.000000,2.000000
21,8,22,Beyond Snack,Kerala Banana Chips,1,50.00000,2.5,2000.00,50.00000,2.5,...,1,0,1,0,0,0,0,2,25.000000,1.250000
22,8,23,Vivalyf Innovations- Easy Life,Prickless Diabetes Testing Machine,1,56.00000,7.5,746.67,56.00000,33.3,...,0,1,0,0,0,1,0,2,28.000000,16.650000
24,9,25,Altor,Smart Helmets,1,50.00000,5.0,1000.00,50.00000,7.0,...,0,0,1,1,0,0,0,2,25.000000,3.500000
25,9,26,Ariro,Wooden Toys,1,50.00000,2.5,2000.00,50.00000,10.0,...,0,0,1,0,0,1,0,2,25.000000,5.000000
27,10,28,Nuutjob,Male Intimate Hygiene,1,25.00000,5.0,500.00,25.00000,20.0,...,0,0,1,1,0,1,0,3,8.333333,6.666667
28,10,29,Meatyour,Eggs,1,30.00000,5.0,600.00,30.00000,20.0,...,0,1,1,0,0,1,0,3,10.000000,6.666667
29,10,30,EventBeep,Student Community App,1,30.00000,2.0,1500.00,30.00000,3.0,...,1,0,1,0,0,1,0,3,10.000000,1.000000
32,11,33,Farda,Customised Streetwear,1,30.00000,10.0,300.00,30.00000,20.0,...,0,0,1,1,0,0,0,2,15.000000,10.000000
35,12,36,LOKA,Metaverse App,1,40.00000,5.0,800.00,40.00000,24.0,...,0,1,1,0,0,1,0,3,13.333333,8.000000
36,13,37,Annie,Braille Literary Device,1,30.00000,5.0,600.00,105.00000,3.0,...,0,1,0,1,0,1,0,3,35.000000,1.000000
37,13,38,Caragreen,Eco-Friendly boxes,1,50.00000,10.0,500.00,50.00000,20.0,...,0,1,0,0,0,1,0,2,25.000000,10.000000
38,13,39,The Yarn Bazaar,Yarn-Trading App,1,50.00000,2.0,2500.00,100.00000,10.0,...,1,1,1,0,0,1,0,4,25.000000,2.500000
39,14,40,The Renal Project,Home Dialysis Treatment,1,100.00000,3.0,3333.33,100.00000,6.0,...,0,0,1,1,0,0,0,2,50.000000,3.000000
44,15,45,Cocofit,Coconut based beverage franchise,1,5.00000,5.0,100.00,0.00005,5.0,...,0,1,1,1,0,0,0,3,0.000017,1.666667
45,16,46,Bamboo India,Bamboo Products,1,80.00000,4.0,2000.00,50.00000,3.5,...,1,1,0,0,0,0,0,2,25.000000,1.750000
47,16,48,Beyond Water,Liquid Water Enhancer,1,75.00000,4.0,1875.00,75.00000,15.0,...,0,0,1,1,0,0,0,2,37.500000,7.500000
48,16,49,Let's Try,Healthy Snacks,1,45.00000,2.0,2250.00,45.00000,12.0,...,0,1,1,0,0,0,0,2,22.500000,6.000000
49,17,50,Find Your Kicks India,Sneaker Resale,1,50.00000,10.0,500.00,50.00000,25.0,...,1,1,1,1,0,1,0,5,10.000000,5.000000
50,17,51,Aas Vidyalaya,EdTech App,1,150.00000,3.0,5000.00,150.00000,15.0,...,1,0,0,1,0,1,0,3,50.000000,5.000000
58,19,59,WeSTOCK,Livestock health monitoring AI,1,50.00000,5.0,1000.00,60.00000,10.0,...,1,0,1,1,0,1,0,4,15.000000,2.500000
63,20,64,IN A CAN,Can Cocktails,1,50.00000,2.0,2500.00,100.00000,10.0,...,1,1,1,1,0,1,0,5,20.000000,2.000000
64,21,65,Get a Whey,Sugar-Free Icecream,1,100.00000,8.0,1250.00,100.00000,15.0,...,1,0,1,0,1,0,0,3,33.333333,5.000000
66,21,67,The Quirky Nari,Customised Apparels,1,35.00000,5.0,700.00,35.00000,24.0,...,0,1,0,0,1,0,0,2,17.500000,12.000000
67,22,68,Hair Originals,Natural Hair Extensions,1,60.00000,2.0,3000.00,60.00000,4.0,...,1,1,0,0,0,1,0,3,20.000000,1.333333
75,24,76,The Sass Bar,Gifts,1,40.00000,8.0,500.00,50.00000,35.0,...,0,1,0,0,0,0,1,2,25.000000,17.500000
79,25,80,Sunfox Technologies,Portable ECG Device,1,100.00000,2.0,5000.00,100.00000,6.0,...,0,1,0,1,1,1,1,5,20.000000,1.200000
85,27,86,Watt Technovations,Ventilated PPE Kits,1,0.00101,10.0,0.01,0.00101,4.0,...,0,1,0,1,0,1,1,4,0.000253,1.000000
88,28,89,Humpy A2,Organic Milk Products,1,75.00000,4.0,1875.00,100.00000,15.0,...,0,0,0,0,1,1,1,3,33.333333,5.000000
90,28,91,Gold Safe Solutions Ind.,Anti-Suicidal Fan Rod,1,50.00000,5.0,1000.00,50.00000,30.0,...,0,0,0,0,1,1,1,3,16.666667,10.000000
91,29,92,Wakao Foods,Jackfruit Products,1,75.00000,5.0,1500.00,75.00000,21.0,...,0,0,0,1,1,0,1,3,25.000000,7.000000
95,30,96,Kabaddi Adda,All-Kabaddi App,1,80.00000,1.0,8000.00,80.00000,6.0,...,0,0,0,1,1,0,0,2,40.000000,3.000000
108,33,109,Tweek Labs,Sportswear,1,40.00000,2.0,2000.00,60.00000,10.0,...,1,1,0,0,0,1,0,3,20.000000,3.333333
109,33,110,Proxgy,VR,1,35.00000,1.0,3500.00,10.00000,10.0,...,1,0,0,0,0,1,0,2,5.000000,5.000000
110,34,111,Nomad Food Project,Bacon Jams,1,40.00000,10.0,400.00,40.00000,20.0,...,1,0,0,1,1,0,1,4,10.000000,5.000000
114,35,115,Jain Shikanji,Lemonade,1,40.00000,8.0,500.00,40.00000,30.0,...,1,1,1,0,1,0,0,4,10.000000,7.500000

In [12]:
d=(df.total_sharks_invested.min(),df.total_sharks_invested.max())
pd.DataFrame(d)

episode_number,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
total_sharks_invested,2,0,0,0,0,0,0,1,0,3,...,0,0,0,0,0,0,0,0,0,0
total_sharks_invested,3,1,1,2,2,5,2,2,2,3,...,1,4,3,3,2,1,1,3,4,4

In [13]:
n=(r[(r['pitcher_ask_amount']>=100) &(r['total_sharks_invested']>0)])
n

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
12,5,13,Revamp Moto,E-Bike,1,100.0,1.0,10000.00,100.0,1.5,...,0,1,1,0,0,0,0,2,50.000000,0.75
18,7,19,Raising Superstars,Child Development App,0,100.0,2.0,5000.00,100.0,4.0,...,1,0,1,0,0,0,0,2,50.000000,2.00
39,14,40,The Renal Project,Home Dialysis Treatment,1,100.0,3.0,3333.33,100.0,6.0,...,0,0,1,1,0,0,0,2,50.000000,3.00
50,17,51,Aas Vidyalaya,EdTech App,1,150.0,3.0,5000.00,150.0,15.0,...,1,0,0,1,0,1,0,3,50.000000,5.00
55,18,56,Otua,Electric Auto Vehicle,1,100.0,1.0,10000.00,1.0,1.0,...,1,0,0,0,0,0,0,1,1.000000,1.00
64,21,65,Get a Whey,Sugar-Free Icecream,1,100.0,8.0,1250.00,100.0,15.0,...,1,0,1,0,1,0,0,3,33.333333,5.00
71,23,72,Namhya Foods,Ayurvedic Enriched Food,1,100.0,5.0,2000.00,50.0,10.0,...,0,0,1,0,0,0,0,1,50.000000,10.00
79,25,80,Sunfox Technologies,Portable ECG Device,1,100.0,2.0,5000.00,100.0,6.0,...,0,1,0,1,1,1,1,5,20.000000,1.20
87,27,88,Insurance Samadhan,Insurance Solutions,1,100.0,1.0,10000.00,100.0,4.0,...,0,0,0,0,0,1,0,1,100.000000,4.00

In [14]:
s=(r[(r['deal_equity']<50)])
s

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
0,1,1,BluePine Industries,Frozen Momos,1,50.0,5.0,1000.0,75.0,16.00,...,1,0,1,0,1,0,0,3,25.0,5.333333
2,1,3,Heart up my Sleeves,Detachable Sleeves,1,25.0,10.0,250.0,25.0,30.00,...,0,1,0,0,1,0,0,2,12.5,15.000000
3,2,4,Tagz Foods,Healthy Potato Chips,1,70.0,1.0,7000.0,70.0,2.75,...,1,0,0,0,0,0,0,1,70.0,2.750000
4,2,5,Head and Heart,Brain Development Course,0,50.0,5.0,1000.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
5,2,6,Agro tourism,Tourism,0,50.0,5.0,1000.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,34,113,Green Protein,Plant-Based Protein,0,60.0,2.0,3000.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
113,34,114,On2Cook,Fastest Cooking Device,0,100.0,1.0,10000.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
114,35,115,Jain Shikanji,Lemonade,1,40.0,8.0,500.0,40.0,30.00,...,1,1,1,0,1,0,0,4,10.0,7.500000
115,35,116,Woloo,Washroom Finder,0,50.0,4.0,1250.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000
116,35,117,Elcare India,Carenting for Elders,0,100.0,2.5,4000.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000

In [15]:
y=(df.brand_name).describe(include="object")
pd.DataFrame(y)

               count unique                        top freq
episode_number
1                  3      3        BluePine Industries    1
2                  3      3                 Tagz Foods    1
3                  3      3                Qzense Labs    1
4                  3      3                      Cosiq    1
5                  3      3                Revamp Moto    1
6                  3      3                Skippi Pops    1
7                  3      3         Raising Superstars    1
8                  3      3               Beyond Snack    1
9                  3      3                      Altor    1
10                 3      3                    Nuutjob    1
11                 3      3                 Gopal's 56    1
12                 3      3             Auli Lifestyle    1
13                 3      3                      Annie    1
14                 3      3          The Renal Project    1
15                 3      3           Hammer Lifestyle    1
16                 4      4               Bamboo India    1
17                 4      4      Find Your Kicks India    1
18                 4      4            Mommy's Kitchen    1
19                 4      4                      Ethik    1
20                 3      3            The State Plate    1
21                 3      3                 Get a Whey    1
22                 4      4             Hair Originals    1
23                 4      4               Namhya Foods    1
24                 3      3               The Sass Bar    1
25                 3      3                  PawsIndia    1
26                 3      3            Isak Fragrances    1
27                 4      4               Theka Coffee    1
28                 3      3                   Humpy A2    1
29                 3      3                Wakao Foods    1
30                 4      4  Sippline Drinking Shields    1
31                 4      4                 Scrapshala    1
32                 4      4               Thea and Sid    1
33                 4      4              Colour Me Mad    1
34                 4      4         Nomad Food Project    1
35                 3      3              Jain Shikanji    1

In [16]:
r.columns[18:25]

Index(['ashneer_deal', 'anupam_deal', 'aman_deal', 'namita_deal',
       'vineeta_deal', 'peyush_deal', 'ghazal_deal'],
      dtype='object')

In [17]:
w=r.columns[18:25]

In [18]:
o=w.value_counts().sum()

In [19]:
o

7

In [20]:
z=[r.ashneer_deal.sum(),r.anupam_deal.sum(),r.aman_deal.sum(),r.namita_deal.sum(),r.vineeta_deal.sum(),r.peyush_deal.sum(),r.ghazal_deal.sum()]
z

[21, 24, 28, 22, 15, 27, 7]

In [21]:
y=r.equity_per_shark.sum()
v=y/7
v

93.32571428571428

In [22]:
k=r['total_sharks_invested'] * r['amount_per_shark']

k.sum()

3742.001060079

In [25]:
r.brand_name.value_counts().sum()

117

In [32]:
zx=[r.ashneer_present.sum(), r.anupam_present.sum(), r.aman_present.sum(), r.namita_present.sum(), r.vineeta_present.sum(), r.peyush_present.sum(), r.ghazal_present.sum()]
zx

[98, 117, 98, 106, 66, 88, 26]

In [33]:
r.columns

Index(['episode_number', 'pitch_number', 'brand_name', 'idea', 'deal',
       'pitcher_ask_amount', 'ask_equity', 'ask_valuation', 'deal_amount',
       'deal_equity', 'deal_valuation', 'ashneer_present', 'anupam_present',
       'aman_present', 'namita_present', 'vineeta_present', 'peyush_present',
       'ghazal_present', 'ashneer_deal', 'anupam_deal', 'aman_deal',
       'namita_deal', 'vineeta_deal', 'peyush_deal', 'ghazal_deal',
       'total_sharks_invested', 'amount_per_shark', 'equity_per_shark'],
      dtype='object')

In [35]:
for index in range(len(zx)):
    print(zx[index])

98
117
98
106
66
88
26